spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/avia
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
ticket:
  comission: 0.025
jwt:
  secret: secret
  duration: 20
#flyway:
#  url: jdbc:postgresql://localhost:5432/avia
#  schemas: public
#  user: postgres
#  password: postgres

